server:
    port: 8083

cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200}"

spring:
    datasource:
        url: "${DB_URL:jdbc:postgresql://127.0.0.1:5432/identity?ssl=false&serverTimezone=UTC}"
        username: "${DB_USER:admin}"
        password: "${DB_PASS:swordfish$fincen1117}"
        driver-class-name: org.postgresql.Driver

    web:
        resources:
            add-mappings: false

    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    time_zone: UTC

    servlet:
        multipart:
            max-file-size: "${MAX_FILE_SIZE:25MB}"
            max-request-size: "${MAX_REQUEST_SIZE:25MB}"

    sql:
        init:
            mode: "${SQL_INIT_MODE:never}"
            platform: postgresql
            continue-on-error: false

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - openid
                            - profile
                            - email
                        redirect-uri: ${GOOGLE_REDIRECT_URI}
                    github:
                        client-id: ${GITHUB_CLIENT_ID}
                        client-secret: ${GITHUB_CLIENT_SECRET}
                        scope:
                            - user:email
                        redirect-uri: ${GITHUB_REDIRECT_URI}
                provider:
                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

    mail:
        host: email-smtp.us-east-1.amazonaws.com
        port: 587
        username: "${SES_SMTP_USERNAME}"
        password: "${SES_SMTP_PASSWORD}"

frontend:
    frontend_url: "${FRONTEND_URL:http://localhost:4200}"

jwt:
    public-key:
    private-key:

aws:
    region: "${AWS_REGION:us-east-1}"
    dynamodb:
        endpoint: "${DDB_ENDPOINT:}"
    s3:
        bucket: "${DOCS_BUCKET:recipe-website-2026}"

management:
    endpoints:
        web:
            exposure:
                include: health,info,env,configprops
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true

logging:
    level:
        com.zaxxer.hikari: ERROR
        org.springframework.jdbc.datasource: ERROR
        root: ERROR
        com.finsight: ERROR
